name: ci-checks

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: 'x64'
    - name: install
      run: |
        pip install -e .[dev,test]
    - name: lint
      run: |
        make lint
    - name: test
      env:
        PUBMED_API_KEY: ${{ secrets.PUBMED_API_KEY }}
      run: |
        make test
